archlinux:
    image: archlinux/base
    stage: test
    before_script:
        - pacman -Syu --noconfirm make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

alpine:
    image: alpine:edge
    stage: test
    before_script:
        - apk add make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

fedora:
    image: fedora
    stage: test
    before_script:
        - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
        - dnf install -y make nodejs npm yarn busybox
        - busybox --install -s
    script:
        - make all
        - make test
    retry: 2
