archlinux:
    image: archlinux/base
    stage: test
    before_script:
        - pacman -Syu --noconfirm make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

termux:
    image: rudloff/termux
    stage: test
    before_script:
        - apt update
        - apt install -y make nodejs yarn
    script:
        - make all
        - make test
    retry: 2

voidlinux:
    image: voidlinux/voidlinux
    stage: test
    before_script:
        - xbps-install -Sy make nodejs yarn
    script:
        - make all
        - make test
    retry: 2

alpine:
    image: alpine:edge
    stage: test
    before_script:
        - apk add make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

fedora:
    image: fedora
    stage: test
    before_script:
        - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
        - dnf install -y make nodejs npm yarn busybox
        - busybox --install -s
    script:
        - make all
        - make test
    retry: 2

nixos:
    image: nixos/nix
    stage: test
    before_script:
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
        - nix-channel --update
        - nix-env -iA nixos.gnumake
        - nix-env -iA nixos.nodejs-11_x
        - nix-env -iA nixos.yarn
    script:
        - make all
        - make test
    retry: 2
