archlinux:
    image: archlinux/base
    stage: test
    before_script:
        - pacman -Syu --noconfirm make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

manjaro:
    image: jonathonf/manjaro
    stage: test
    before_script:
        - pacman -Syu --noconfirm make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

voidlinux:
    image: zaoqi/voidlinux-ci
    stage: test
    before_script:
        - xbps-install -Sy make nodejs yarn
    script:
        - make all
        - make test
    retry: 2

alpine:
    image: alpine:edge
    stage: test
    before_script:
        - apk add make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

fedora:
    image: fedora
    stage: test
    before_script:
        - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
        - dnf install -y make nodejs npm yarn findutils
    script:
        - make all
        - make test
    retry: 2

centos:
    image: centos:7
    stage: test
    before_script:
        - curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
        - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - yum install -y make nodejs npm yarn
        - npm i -g npx
    script:
        - make all
        - make test
    retry: 2

nixos:
    image: nixos/nix
    stage: test
    before_script:
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
        - nix-channel --update
        - nix-env -iA nixos.gnumake
        - nix-env -iA nixos.nodejs-11_x
        - nix-env -iA nixos.yarn
    script:
        - make all
        - make test
    retry: 2

debian:
    image: debian
    stage: test
    before_script:
        - apt-get update && apt-get install -y curl gnupg
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        - apt-get update && apt-get install -y make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2

ubuntu:
    image: ubuntu
    stage: test
    before_script:
        - apt-get update && apt-get install -y curl gnupg
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        - apt-get update && apt-get install -y make nodejs npm yarn
    script:
        - make all
        - make test
    retry: 2
