language: bash
matrix:
  include:
    - os: windows
      install:
        - choco install make nodejs yarn
        - export PATH="$PATH:/c/Program Files (x86)/Yarn/bin:/c/Program Files/nodejs" # yarn & nodejs doesn't support `Shimming`
    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          packages:
            - make
            - nodejs
            - npm
            - yarn
    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - make
            - nodejs
            - npm
            - yarn
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'deb https://dl.yarnpkg.com/debian stable main'
              key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
          packages:
            - make
            - nodejs
            - npm
            - yarn
script:
  - make all
  - make test
